version: '3'

services:
  web:
    image: tiangolo/uvicorn-gunicorn-fastapi:python3.8
    container_name: your_project_name
    ports:
      - "8000:80"
    volumes:
      - ./app:/app
    depends_on:
      - db

  db:
    image: "keinos/sqlite3:latest"
    container_name: your_project_db_name
    volumes:
      - ./data:/data
